sudo: required

dist: xenial

service:
   - docker

stages:
  - if: branch = master
    name: master build
  - if: branch = dev
    name: dev build
  - name: branch build

jobs:
  include:
  - stage: master build
    script:
      - version=0.1
      - docker build -t weselixir/proTES:"$version" -t weselixir/proTES:master .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - if [ "$TRAVIS_PULL_REQUEST" = false ]; then docker push "$DOCKER_REPO_NAME":"$version"; fi
  - stage: dev build
    script:
      - docker build -t weselixir/proTES:dev -t weselixir/proTES:build-"$TRAVIS_BUILD_NUMBER" .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - if [ "$TRAVIS_PULL_REQUEST" = false ]; then docker push "$DOCKER_REPO_NAME":build-"$TRAVIS_BUILD_NUMBER"; fi
  - stage: branch build
    script:
      - docker build -t weselixir/proTES-branched:build-"$TRAVIS_BUILD_NUMBER" .