version: '3.6'
services:

  celery-worker-protes:
    image: protes:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - rabbit-protes
    command: bash -c "cd /app/pro_tes; celery worker -A celery_worker -E --loglevel=info"
    volumes:
      - ../data:/data

  protes:
    image: protes:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - mongo-protes
    command: bash -c "cd /app/pro_tes; gunicorn -c config.py wsgi:app"
    volumes:
      - ../data:/data

  rabbit-protes:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    links:
      - mongo-protes

  mongo-protes:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ../data/db:/data/db
