# General server/service settings
server:
    port: 8081

# Security settings
security:
    authorization_required: True

# Database settings
database:
    host: 'mongo'
    name: pro-tes-db-dev

# Storage
storage:
    permanent_dir: '/data/output'
    tmp_dir: '/data/tmp'

# Celery task queue
celery:
    broker_host: 'localhost'
    broker_port: 5672

# OpenAPI specs

# TES service info settings

# TES server
