# General server/service settings

# Security settings
security:
    authorization_required: False

# Database settings
database:
    host: 'mongo-protes'
    name: pro-tes-db-dev

# Celery task queue
celery:
    broker_host: 'rabbit-protes'

# OpenAPI specs

# TES service info settings

# TES server
