# General server/service settings
server:
    debug: False
    environment: production
    testing: False
    use_reloader: False

# Security settings
security:
    authorization_required: True

# Database settings
database:
    host: 'mongo-protes'

# Celery task queue
celery:
    broker_host: 'rabbit-protes'

# OpenAPI specs

# TES service info settings

# TES server
