# General server/service settings
server:
    port: 8090

# Security settings
security:
    authorization_required: False

# Database settings
database:
    host: 'mongo-protes'
    port: 27027
    name: pro-tes-db-dev

# Storage
storage:
    permanent_dir: '/data/output'
    tmp_dir: '/data/tmp'

# Celery task queue
celery:
    broker_host: 'rabbit-protes'
    broker_port: 5682

# OpenAPI specs

# TES service info settings

# TES server
